version: "3.8"

services:
  api:
    build:
      context: ./CMAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    networks:
      - cmapi-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - cmapi-network

networks:
  cmapi-network:
    driver: bridge

volumes:
  redis-data:
